#!/bin/bash

export VAMPLEAN_PATH=$(pwd)/../vamplean/.lake/build/lib/lean/
export VAMPIRE_BINARY=$(pwd)/./vampire
export LEAN_BINARY=$(pwd)/../requirements/elan/toolchains/leanprover--lean4---v4.31.0/bin/lean

TIMELIMIT_OPTION="-t 30"
# check if $STAREXEC_WALLCLOCK_LIMIT is set and if so, include -t option with the value of $STAREXEC_WALLCLOCK_LIMIT
if [ -n "$STAREXEC_WALLCLOCK_LIMIT" ]; then
    TIMELIMIT_OPTION="-t $STAREXEC_WALLCLOCK_LIMIT"
fi

./valeadate-musl $TIMELIMIT_OPTION --accept-new-symbols $1 -p $2 --vv